import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "./components/PrelineScript";
import NavMenu from "./components/NavMenu";
import FooterComp from "./components/FooterComp";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <NavMenu></NavMenu>
   
        {children}


        <FooterComp></FooterComp>  
      
        </body>

      <PrelineScript />
    </html>
  );
}


 
